#!/bin/bash
# Run the 2026-05-08 mode-subset Stage-1 pilot (18 cells, ~4.5 hr total).
# 6 mode subsets x 3 pilot seeds {42, 123, 7} at fixed ff=0.5.
# Each cell: 200-iter fine-tune on slippery + eval on rough+slippery.
# Compared seed-paired against existing n=3 ff=0.0 multiseed_pilot baseline
# (results/multiseed_pilot_2026-05-07_failure_fraction=0p0_seed=*).
set -uo pipefail

ASHFALL_ROOT="/home/yusuf/Projects/ashfall"
LOGS_DIR="$ASHFALL_ROOT/results/_logs"
mkdir -p "$LOGS_DIR"

# Subset outer, seed inner — matches the run-doc spec. Subset names track
# the labels in src/ashfall/experiment/sweep.py::_FAILURE_MODES_LABELS.
SUBSETS=(
    "all_modes"
    "slip_only"
    "command_mismatch_only"
    "slip_plus_cm"
    "severe_only"
    "severe_plus_slip"
)
SEEDS=(42 123 7)

# Cells are generated across multiple seconds, so each cell may have a
# different stamp dir. Resolve per-cell at run time. SKIP_DONE=1 in the
# environment skips cells whose metrics_{rough,slippery}.json already
# exist (used to resume after the sweep is restarted mid-run).
SKIP_DONE="${SKIP_DONE:-0}"

MANIFEST="$LOGS_DIR/failure_modes_pilot_manifest.txt"
if [ ! -f "$MANIFEST" ]; then
    echo "# Ashfall mode-subset Stage-1 pilot manifest" > "$MANIFEST"
    echo "# started: $(date -Is)" >> "$MANIFEST"
fi

OVERALL_START=$SECONDS

for subset in "${SUBSETS[@]}"; do
    for seed in "${SEEDS[@]}"; do
        CELL_NAME="failure_modes_pilot_2026-05-08_failure_modes=${subset}_seed=${seed}"
        CELL_PARENT="$ASHFALL_ROOT/results/${CELL_NAME}"
        LOG="$LOGS_DIR/failure_modes_pilot_${subset}_seed_${seed}.log"
        # Pick the latest stamp dir under the cell parent (alphabetical
        # sort works for ISO timestamps). Cells are pre-generated by
        # scripts/run_ablation.sh, so this dir must exist.
        CELL_DIR=$(ls -d "${CELL_PARENT}"/*/ 2>/dev/null | sort | tail -1)
        CELL_DIR="${CELL_DIR%/}"
        echo "" | tee -a "$MANIFEST"
        echo "=== Cell ${subset} seed=${seed} === $(date -Is)" | tee -a "$MANIFEST"
        if [ -z "$CELL_DIR" ] || [ ! -d "$CELL_DIR" ]; then
            echo "MISSING: ${CELL_PARENT} (no stamp dir)" | tee -a "$MANIFEST"
            exit 2
        fi
        # Resume support: if both eval metric files already exist and
        # SKIP_DONE=1, treat the cell as done.
        if [ "$SKIP_DONE" = "1" ] \
            && [ -f "$CELL_DIR/metrics/metrics_rough.json" ] \
            && [ -f "$CELL_DIR/metrics/metrics_slippery.json" ]; then
            echo "Cell ${subset} seed=${seed} rc=0 duration=0s (skipped, already done)" \
                | tee -a "$MANIFEST"
            continue
        fi
        START=$SECONDS
        bash "$CELL_DIR/commands.sh" 2>&1 | tee "$LOG" | tail -3
        RC=${PIPESTATUS[0]}
        DUR=$((SECONDS - START))
        echo "Cell ${subset} seed=${seed} rc=$RC duration=${DUR}s" | tee -a "$MANIFEST"
        if [ $RC -ne 0 ]; then
            echo "Cell ${subset} seed=${seed} FAILED, stopping sweep." | tee -a "$MANIFEST"
            exit 1
        fi
    done
done

OVERALL_DUR=$((SECONDS - OVERALL_START))
echo "" | tee -a "$MANIFEST"
echo "# completed: $(date -Is)" | tee -a "$MANIFEST"
echo "# total duration: ${OVERALL_DUR}s" | tee -a "$MANIFEST"
